Calories_calculator/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django_registration.backends.one_step.views import RegistrationView
from django.contrib.auth.views import LogoutView, LoginView
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static

from core.forms import CustomUserForm
from core.views import Index, Profile, CategoryView, ChoiceCategoryView, ProductsView, ProductOffer, Statistics, Settings
# from core.forms import CustomUserForm
# from core.views import Index, Profile, CategoryView, ProductsView, ChoiceCategoryView, Statistics, Settings, \
#     ProductOffer

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Index.as_view()),
    path('accounts/register/', RegistrationView.as_view(success_url='/', form_class=CustomUserForm),
         name='django_registration_register'),
    path('accounts/', include('django_registration.backends.activation.urls')),
    path('accounts/registration/', LoginView.as_view(), name='registration'),
    path('accounts/profile/', Profile.as_view(), name='profile'),
    path('accounts/profile/<int:pk>', Profile.as_view(), name='user_profile'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),
    path('change-password/',
         auth_views.PasswordChangeView.as_view(template_name='registration/password_change_form.html'),
         name='password_change'),
    path('change-password/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('category/<int:pk>', CategoryView.as_view(), name='category'),
    path('product/<int:pk>', ProductsView.as_view(), name='product'),
    path('product/offer', ProductOffer.as_view(), name='product_offer'),
    path('choice_category/', ChoiceCategoryView.as_view(), name='choice_category'),
    path('statistics/<int:pk>', Statistics.as_view(), name='statistics'),
    path('settings/', Settings.as_view(), name='settings'),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

core/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import pre_save
from django.dispatch import receiver


class CreatedUpdated(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Category(models.Model):
    name = models.CharField(max_length=255)
    image = models.ImageField("Изображения", upload_to="categories/", default='categories/anonymous.jpg')

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    calories = models.FloatField(max_length=10)
    proteins = models.FloatField(max_length=10)
    fats = models.FloatField(max_length=10)
    carbohydrates = models.FloatField(max_length=10)
    image = models.ImageField("Изображения", upload_to="products/", default='products/anonymous.jpg')
    is_deleted = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class Reward(models.Model):
    THIN_FOR_THE_WEEK = 1
    THIN_FOR_THE_MONTH = 2
    THIN_FOR_THE_YEAR = 3
    FAT_FOR_THE_WEEK = 4
    FAT_FOR_THE_MONTH = 5
    FAT_FOR_THE_YEAR = 6

    REWARDS_CHOICES = (
        (THIN_FOR_THE_WEEK, 'Наилегчайший недели'),
        (THIN_FOR_THE_MONTH, 'Наилегчайший месяца'),
        (THIN_FOR_THE_YEAR, 'Наилегчайший года'),
        (FAT_FOR_THE_WEEK, 'Тяжеловес недели'),
        (FAT_FOR_THE_MONTH, 'Тяжеловес месяца'),
        (FAT_FOR_THE_YEAR, 'Тяжеловес года'),
    )
    title = models.PositiveIntegerField(choices=REWARDS_CHOICES, null=True)


class CustomUser(AbstractUser):
    STAT_FOR_THE_WEEK = 1
    STAT_FOR_THE_MONTH = 2
    STAT_FOR_ALL_TIME = 3

    NONE = 1
    MALE = 2
    FEMALE = 3

    STATISTICS_CHOICES = (
        (STAT_FOR_THE_WEEK, 'За неделю'),
        (STAT_FOR_THE_MONTH, 'За месяц'),
        (STAT_FOR_ALL_TIME, 'Вся')
    )
    GENDER_CHOICES = (
        (NONE, 'Не определено'),
        (MALE, 'Мужчина'),
        (FEMALE, 'Женщина')
    )
    image = models.ImageField("Изображения", upload_to="photo/", default='photo/anonymous.jpg')
    user_weight = models.FloatField(max_length=5, null=True)
    user_height = models.FloatField(max_length=5, null=True)
    user_calories = models.FloatField(max_length=255, default=0)
    statistic = models.PositiveSmallIntegerField(choices=STATISTICS_CHOICES, default=3)
    body_mass_index = models.FloatField(max_length=5, null=True)
    age = models.PositiveSmallIntegerField(default=0)
    gender = models.PositiveSmallIntegerField(choices=GENDER_CHOICES, default=1)


class UserProduct(CreatedUpdated):
    prod_id = models.ForeignKey(Product, on_delete=models.CASCADE)
    user_id = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    weight = models.FloatField(max_length=10)
    us_pr_calories = models.FloatField(max_length=255, default=0)


class UserReward(CreatedUpdated):
    reward_id = models.ForeignKey(Reward, on_delete=models.CASCADE)
    user_id = models.ForeignKey(CustomUser, on_delete=models.CASCADE)


@receiver(pre_save, sender=CustomUser)
def user_pre_save_action(sender, instance, **kwargs):
    if instance.user_weight and instance.user_height:
        instance.body_mass_index = instance.user_weight / ((instance.user_height / 100) * (instance.user_height / 100))

templates/profile/profile.html
{% extends 'base.html' %}
{% load static %}
{% block navbar %}
    <div class="row">
        <div class="col-6">
            <center>
                <h4 style="margin-top:10px">{{ custom_user.username }}</h4>
                <img src="{{ custom_user.image.url }}" width="250" height="250" style="margin-top:20px"/>
                <h3 style="margin-top:20px">Вес: {{ custom_user.user_weight }}</h3>
                <h3>Рост: {{ custom_user.user_height }}</h3>
                <h3>Возраст: {{ custom_user.age }}</h3>
                <h3>Пол: {{ gender }}</h3>
                <h3>Индекс массы тела: {{ custom_user.body_mass_index|floatformat:2 }}</h3>
                <h3>Калорий набрано: {{ custom_user.user_calories|floatformat:2 }}</h3>
            </center>
        </div>
        <div class="col-6">
            <h4 class="text-center" style="margin-top:10px">Статистика {{ period|lower }}</h4>
            <div class="dropdown-divider"></div>
            <table class="table table-borderless" style="width: 600px ">
                <thead class="t">
                <tr>
                    <th>Продукт</th>
                    <th>Вес</th>
                    <th>Калорийность</th>
                    <th>Дата</th>
                </tr>
                </thead>
                {% for product in products %}
                    <tbody>
                    <tr>
                        <td>{{ product.prod_id }}</td>
                        <td>{{ product.weight }}</td>
                        <td>{{ product.us_pr_calories|floatformat:1 }}</td>
                        <td>{{ product.created_at }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <h4 class="text-center">Всего калорий набрано за это время: {{ summary|floatformat:2 }}</h4>
            <h4 class="text-center" style="margin-top:20px">Все награды</h4>
            <div class="dropdown-divider"></div>
            <table class="table table-borderless" style="width: 600px">
                <thead class="t">
                <tr>
                    <th>Наименование</th>
                    <th>Дата получения</th>
                </tr>
                </thead>
                {% for reward in rewards %}
                    <tbody>
                    <tr>
                        <td>{{ reward.reward_id.get_title_display }}</td>
                        <td>{{ reward.created_at }}</td>
                        <td>{{ reward.title }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

templates/profile/settings.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block navbar %}
    <form method="post" enctype="multipart/form-data">{% csrf_token %}
        <table class="text-center">
            {% bootstrap_form form %}
            <tr>
                <td>
                    <button type="submit" class="btn btn-light">Сохранить</button>
                    <a href="{% url 'password_change' %}">
                        <button type="button" class="btn btn-primary">Сменить пароль</button>
                    </a>
                </td>
            </tr>
        </table>
    </form>
{% endblock %}

templates/profile/user_stats.html
{% extends 'base.html' %}

{% block navbar %}
    <div class="row" style="margin-top:15px">
        <div class="col-3">
            <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Выбрать период
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <a class="dropdown-item" href="{% url 'statistics' pk=2 %}">День</a>
                    <a class="dropdown-item" href="{% url 'statistics' pk=3 %}">Неделя</a>
                    <a class="dropdown-item" href="{% url 'statistics' pk=4 %}">Месяц</a>
                </div>
            </div>
        </div>
        <div class="col-9">
            <h4 style="margin-left:150px">{{ period }}</h4>
            <div class="dropdown-divider" style="width: 600px"></div>
            <table class="table table-borderless" style="width: 700px">
                <thead class="t">
                <tr>
                    <th>Продукт</th>
                    <th>Вес</th>
                    <th>Калорийность</th>
                    <th>Дата</th>
                </tr>
                </thead>
                {% for product in products %}
                    <tbody>
                    <tr>
                        <td>{{ product.prod_id }}</td>
                        <td>{{ product.weight }}</td>
                        <td>{{ product.us_pr_calories|floatformat:1 }}</td>
                        <td>{{ product.created_at }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <h4>Всего калорий набрано за выбранный период: {{ summary|floatformat:2 }}</h4>
        </div>
    </div>
{% endblock %}